@url=http://localhost:3000

### Listado de tareas
GET {{url}}/tareas

### Listado de tareas completadas
GET {{url}}/tareas?estado=completada

### Listado de tareas pendientes
GET {{url}}/tareas?estado=pendiente

### Filtro de estado invalido
GET {{url}}/tareas?estado=enproceso

### Detalle de tarea
GET {{url}}/tareas/1

### Detalle con id invalido
GET {{url}}/tareas/algo

### Crear tarea
POST {{url}}/tareas
Content-Type: application/json

{
    "nombre": "Comprar pan"
}

### Crear tarea completada
POST {{url}}/tareas
Content-Type: application/json

{
    "nombre": "Lavar platos",
    "completada": true
}

### Crear tarea duplicada
POST {{url}}/tareas
Content-Type: application/json

{
    "nombre": "comprar pan"
}

### Crear tarea invalida
POST {{url}}/tareas
Content-Type: application/json

{
    "nombre": "",
    "completada": "si"
}

### Modificar tarea
PUT {{url}}/tareas/1
Content-Type: application/json

{
    "nombre": "Comprar leche",
    "completada": true
}

### Quitar tarea
DELETE {{url}}/tareas/1
